#                            **THEORY**
**Question:1**  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
**Answer:** **Purpose:** NumPy (Numerical Python) is a library for efficient numerical computation in Python, designed to provide support for large, multi-dimensional arrays and matrices, and a wide range of high-performance mathematical functions to manipulate them. Its primary purpose is to facilitate scientific computing and data analysis in Python.

**Advantages:**

**Efficient Array Operations:** NumPy arrays are stored in a contiguous block of memory, allowing for fast and efficient operations, such as element-wise arithmetic, indexing, and reshaping.

**Support for Advanced Mathematical Functions:** NumPy provides an extensive range of mathematical functions, including trigonometric, statistical, and linear algebra routines, making it an ideal choice for scientific computing and data analysis.

**Enhancing Python’s Capabilities:**
1.Efficient and flexible array operations

2.Advanced mathematical functions

3.Seamless integration with other scientific computing libraries

4.Robust support for scientific computing and data analysis

**Question:2**  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

**Answer:-**
The np.mean() method returns the arithmetic mean, but the np.average() function returns the algebraic mean if no additional parameters are specified, but it may also be used to compute a weighted average.

The term "mean" often refers to the "arithmetic mean", which is the sum of a
set of numbers divided by the total number of the numbers in the set.

The term "average" refers to a variety of computations, the "arithmetic mean" is one of them. Other terms include 'median,' 'mode,' 'weighted mean,' 'interquartile mean,' and a variety of others.


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
np.mean(arr)


5.0

In [4]:
array2 = np.arange(15)
print('array:\n', array2)
print('average when no weights were specified : ',np.average(array2))
print('average when weights were specified : ',np.average(array2,weights=range(15,0,-1)))


array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
average when no weights were specified :  7.0
average when weights were specified :  4.666666666666667


**Question:3** Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

**Answer:**
Some of the most frequent methods for reversing a numpy array are as follows:


*   Using the flip() function
*   Using the reverse() function




In [8]:
# Example for 2D with the help of flip() function
import numpy as np
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr)
print(arr)
print('Reversed array')
print(reversed_arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reversed array
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [13]:
# Example for 1D with the help of reverse() function
import array

arr=array.array('i',[1,2,6,8,4,2])
print(arr)
arr.reverse()
print("Reversed Array:",arr)


array('i', [1, 2, 6, 8, 4, 2])
Reversed Array: array('i', [2, 4, 8, 6, 2, 1])


**Question:4**   How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

**Answer:**
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.


*   i - integer
*   b - boolean
*   f - float
*   S - string
*   O - object










In [1]:
# integer
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [2]:
# string
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


**Importance of data types in memory management and performance.**

1. Enable efficient memory allocation and deallocation
2. Optimize cache performance
3. Guide page replacement algorithms
4. Influence memory access patterns and CPU performance
5. Facilitate garbage collection and memory protection
6. Inform code generation and optimization

**Question:6**  Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

**Answer:-**
In NumPy, an ndarray (N-dimensional array) is a multi-dimensional array of fixed size, composed of elements of the same data type. It is a fundamental data structure in NumPy, designed for efficient numerical computation and manipulation of large datasets.

**Key features:-**

**Homogeneous elements:** All elements in an ndarray have the same data type, such as integers, floats, or complex numbers.

**Fixed size:** The size of an ndarray is determined at creation and cannot change dynamically like Python lists.

**Multi-dimensional:** Ndarrays can have any number of dimensions (1D, 2D, 3D, etc.), allowing for efficient representation and manipulation of complex data structures.
**Contiguous memory allocation:** Ndarrays store elements in contiguous blocks of memory, which improves cache locality and reduces memory access overhead.

**Indexing and slicing:** Ndarrays support advanced indexing and slicing, allowing for flexible selection of sub-arrays and individual elements.

Ndarrays in NumPy are designed for efficient numerical computation and data manipulation, offering features like vectorized operations, broadcasting, and contiguous memory allocation. While Python lists are suitable for general-purpose data storage and manipulation, ndarrays are specifically tailored for numerical computing and provide significant performance and memory advantages.

**Question:6** Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

**Answer:-**

**Numpy array:-**

1. We can create an N-dimensional array in Python using Numpy.array().
2. The array is by default Homogeneous, which means data inside an array must be of the same Datatype.
3. Element-wise operation is possible.
4. Numpy array has various functions, methods, and variables, to ease our task of matrix computation.
5. Elements of an array are stored contiguously in memory. For example, all rows of a two-dimensioned array must have the same number of columns. A three-dimensional array must have the same number of rows and columns on each card.

In [ ]:
# One dimensional
import numpy as np

a = np.array([1, 2, 3])
print(a)


In [ ]:
# Multi dimensional
import numpy as np

a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)


**Python List:-**
1. The list can be homogeneous or heterogeneous.
2. Element-wise operation is not possible on the list.
3. Python list is by default 1-dimensional. But we can create an N-Dimensional list. But then too it will be 1 D list storing another 1D list
4. Elements of a list need not be contiguous in memory.

In [3]:
list = ["Pw", "skills", "Avaneesh"]
print(list)


['Pw', 'skills', 'Avaneesh']


**Question:7**  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

**Answer:-**

**vstack():** Vertically stacks arrays, concatenating them along the first axis (rows). This means that arrays must have the same number of columns.

**hstack():** Horizontally stacks arrays, concatenating them along the second axis (columns). This means that arrays must have the same number of rows.


In [4]:
# vstack
import numpy as np

a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
c = np.vstack((a, b))

print(c)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [5]:
#hstack
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a, b))

print(c)

[1 2 3 4 5 6]


**Question:8** Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

**Answer:-**

**fliplr()**

1. Flips an array along the 1st axis (left/right direction), preserving the 2nd and higher axes.

2. Only works for 2-D and higher-dimensional arrays.
 3.For 2-D arrays, it flips the columns (i.e., the 1st axis).
For higher-dimensional arrays, it flips the 1st axis (e.g., the columns in a 3-D array).

Example: a = np.array([[1, 2], [3, 4]])

result: [[2, 1], [4, 3]]

**flipud()**

1. Flips an array along the 0th axis (up/down direction), preserving the 1st and higher axes.

2. Works for 1-D and higher-dimensional arrays.

3. For 1-D arrays, it simply reverses the order of elements.

4. For 2-D arrays, it flips the rows (i.e., the 0th axis).

5. For higher-dimensional arrays, it flips the 0th axis (e.g., the rows in a 3-D array).

Example: a = np.array([[1, 2], [3, 4]])

result: [[4, 3], [2, 1]]

**Question:9**  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

**Answer:- **

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [7]:
#Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


**Question:10** Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

**Answer:-**

In [8]:
#broadcasting
import numpy as np

a = np.array([10, 20, 30, 40])
a + 5

array([15, 25, 35, 45])

In [9]:
#victorization
d = np.zeros(a.size - 1)
for i in range(len(a) - 1):
    d[i] = a[i + 1] - a[i]
d

array([10., 10., 10.])

#                                   **Practical Questions:**


**Question:1**  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [13]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print(arr)
print("After Interchange rows and columns")
# Interchange rows and columns
arr_transposed = arr.transpose()  # or arr.T

print(arr_transposed)

[[95 91 76]
 [21 88 45]
 [58 34 75]]
After Interchange rows and columns
[[95 21 58]
 [91 88 34]
 [76 45 75]]


**Question:2** Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [18]:
import numpy as np
a  = np.random.randint(1,10, size= (2,5))
print(a)
print('After reshape')
b = a.reshape(5,2)
print(b)

[[6 9 1 2 7]
 [2 3 8 2 8]]
After reshape
[[6 9]
 [1 2]
 [7 2]
 [3 8]
 [2 8]]


**Question:3** Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


In [19]:
import numpy as np

# Create a 4x4 array with random float values
array = np.random.rand(4, 4)

# Add a border of zeros around it
bordered_array = np.pad(array, 1, mode='constant', constant_values=0)

print(bordered_array)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.89360759 0.25192686 0.66682661 0.25227899 0.        ]
 [0.         0.34834053 0.04062013 0.27757836 0.69079126 0.        ]
 [0.         0.58133211 0.54246637 0.73972362 0.15502532 0.        ]
 [0.         0.65736684 0.04927529 0.51151804 0.20706572 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**Question:4** Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [20]:
import numpy as np

arr = np.arange(10, 61, 5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


**Question:5** Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [21]:
a= np.array(['python', 'numpy', 'pandas'])
print(a)
print('Uppercase')
print(np.char.upper(a))
print('Lowercase')
print(np.char.lower(a))
print('Titlecase')
print(np.char.title(a))

['python' 'numpy' 'pandas']
Uppercase
['PYTHON' 'NUMPY' 'PANDAS']
Lowercase
['python' 'numpy' 'pandas']
Titlecase
['Python' 'Numpy' 'Pandas']


**Question:6** Generate a NumPy array of words. Insert a space between each character of every word in the array

In [25]:
import numpy as np
# creating array of string
x = np.array(["Avaneesh", "Kumar", "Pandey"])
print("Printing the Original Array:")
print(x)
# inserting space using np.char.join()
r = np.char.join(" ", x)
print("Printing the array after inserting space between the elements")
print(r)


Printing the Original Array:
['Avaneesh' 'Kumar' 'Pandey']
Printing the array after inserting space between the elements
['A v a n e e s h' 'K u m a r' 'P a n d e y']


**Question:7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [28]:
a = np.random.randint(1,3,(3,3))
b = np.random.randint(1,3,(3,3))
print(a)
print(b)
print('Addition')
print(a+b)
print('Subtraction')
print(a-b)
print('Multiplication')
print(a*b)
print('Division')
print(a/b)

[[1 1 1]
 [1 1 2]
 [1 1 1]]
[[1 2 1]
 [2 2 1]
 [2 1 1]]
Addition
[[2 3 2]
 [3 3 3]
 [3 2 2]]
Subtraction
[[ 0 -1  0]
 [-1 -1  1]
 [-1  0  0]]
Multiplication
[[1 2 1]
 [2 2 2]
 [2 1 1]]
Division
[[1.  0.5 1. ]
 [0.5 0.5 2. ]
 [0.5 1.  1. ]]


**Question:8**  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [30]:
import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)
print("Diagonal elements are")
diagonal_elements = np.diagonal(identity_matrix)
print(diagonal_elements)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements are
[1. 1. 1. 1. 1.]


**Question:9** Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

In [37]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_numbers = np.random.randint(0, 1001, 100)

# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

# Find prime numbers in the array
prime_numbers = [num for num in random_numbers if is_prime(num)]

# Display the prime numbers
print("Prime numbers in the array:", prime_numbers)

Prime numbers in the array: [577, 383, 787, 269, 739, 97, 73, 97, 491, 593, 163, 409, 97, 953, 821]


**Question:10** Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [39]:
import numpy as np
daily_temperatures = np.random.randint(30, 47, 30)
weekly_averages = np.reshape(daily_temperatures, (6, 5)).mean(axis=1)

# Display the weekly averages
print("Weekly average temperatures:")
print(weekly_averages)

Weekly average temperatures:
[39.  39.6 37.8 37.8 37.2 36.8]
